### PR TITLE
bugfix: iban should be dumped.

### PR DESCRIPTION
**Pull request by fsalomon**

### CODE REVIEW

**Comment by mawie86** [comment]
"iban" and "cents" are not attributes of payment Object (that what api returns). "iban" and "cents" are special flags to create payments

**Comment by fsalomon** [comment]
Alright. In that case see https://github.com/figo-connect/php-figo/pull/21

**Comment by fsalomon** [comment]
Hmm, I just realized that doesn't work either, because $payment->dump() is called. So what's the proper way to add a payment if not 

    $payment = new Payment($session, [
      ...
      'iban' => 'DExxxxx',
      'cents' => true
      ...
    ]);
    $session->add_payment($payment);

?

**Comment by mawie86** [comment]
Hi fsalomon, 
Currently our PHP SDK cannot handle this flag. We updated our REST API-  but not the SDK.

We have a ticket to develop this in the future. As workaround you can use follow commands:

```
public function my_special_function($account_id) {
        $my_special_flags = array(
            'iban' => 'DExxxxx',
            'cents' => true
        );
        $response = $this->query_api("/rest/accounts/".$account_id."/payments", $my_special_flags, "POST");
        return (is_null($response) ? null : new Payment($this, $response));
    }
```

For more Information see http://docs.figo.io/#create-a-single-payment

thx and greetings

Matthias

**Pull request closed without merging**
